baseURL = "https://vlucet.github.io/"
languageCode = "en-us"
title = "Val. Lucet"
theme = "researcher"
enableEmoji = true

[params]
  author = "Valentin Lucet"
  description = "Description goes here"
  # favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = ""  # url or path to a logo to put in the header
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "1000px"
    avatarSize = "120px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1